name = "pawelgrzybek"
license = "MIT"
licenselink = ""
description = ""
homepage = "https://pawelgrzybek.com"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Paweł Grzybek"
  homepage = "https://pawelgrzybek.com"
